LABELS = [
    "O",

    "B-INVOICE_NO", "I-INVOICE_NO",
    "B-INVOICE_DATE", "I-INVOICE_DATE",

    "B-SELLER_NAME", "I-SELLER_NAME",
    "B-SELLER_ADDRESS", "I-SELLER_ADDRESS",
    "B-SELLER_PHONE", "I-SELLER_PHONE",
    "B-SELLER_EMAIL", "I-SELLER_EMAIL",
    "B-SELLER_GST_NO", "I-SELLER_GST_NO",
    "B-SELLER_PAN_NO", "I-SELLER_PAN_NO",
    "B-SELLER_STATE", "I-SELLER_STATE",

    "B-BUYER_NAME", "I-BUYER_NAME",
    "B-BUYER_ADDRESS", "I-BUYER_ADDRESS",
    "B-BUYER_PHONE", "I-BUYER_PHONE",
    "B-BUYER_EMAIL", "I-BUYER_EMAIL",
    "B-BUYER_GST_NO", "I-BUYER_GST_NO",
    "B-BUYER_PAN_NO", "I-BUYER_PAN_NO",
    "B-BUYER_STATE", "I-BUYER_STATE",

    "B-ITEM_NAME", "I-ITEM_NAME",
    "B-ITEM_QTY", "I-ITEM_QTY",
    "B-ITEM_UNIT_RATE", "I-ITEM_UNIT_RATE",

    "B-TOTAL_AMOUNT", "I-TOTAL_AMOUNT",

    "B-BANK_NAME", "I-BANK_NAME",
    "B-ACCOUNT_NUMBER", "I-ACCOUNT_NUMBER",
    "B-IFSC_CODE", "I-IFSC_CODE",

    "B-CGST", "I-CGST",
    "B-SGST", "I-SGST",
    "B-IGST", "I-IGST",
]
